---

  - hosts: all 
    become: true
    tasks:

    - name: this task targets apache2 removing.
      ansible.builtin.package:
        name: apache2 
        state: absent # kaldırma işlemini burada yapıyoruz "absent" remove veya uninstall anlamına gelmez mevcut olmayan yani sende olmayan hali anlamına geliyor.

    - name: this task targets Php removing.
      ansible.builtin.package:
        name: libapache2-mod-php 
        state: absent # kaldırma işlemini burada yapıyoruz "absent" remove veya uninstall anlamına gelmez mevcut olmayan yani sende olmayan hali anlamına geliyor.
    
    - name: this task targets docker removing.
      ansible.builtin.package:
        name: docker 
        state: absent # kaldırma işlemini burada yapıyoruz "absent" remove veya uninstall anlamına gelmez mevcut olmayan yani sende olmayan hali anlamına geliyor.
      when : ansible_distribution == "Ubuntu"