---
  - hosts: all 
    become: true # sudo all
    tasks:

    - name: this task is for targets server updates (Bu Görev Hedef Ubuntu sunucuların Update & Upgrade gerçekleştirir.)
      ansible.builtin.package : #burada apt de kullanabilir çünkü hedef sunucu ubuntu
          upgrade: dist #
          update_cache: yes
      when: ansible_distribution == "Ubuntu"


    - name: this task is for targets server updates (Bu Görev Rocky Linux sunucuların Update & Upgrade gerçekleştirir.)
      ansible.builtin.package :
          upgrade_only: yes 
          update_cache: yes
      when: ansible_distirbution == "Rocky"


  # Bu görev, Ubuntu & Rocky Linux için Apache & Php Kütüphanesininn yüklemesini gerçekleştirir.
  - hosts: ubuntu_Server
    become: true
    tasks: 

      - name: İşletim sistemlerini tespit et.
        debug: var=ansible_os_family

      - name: Dosyalardan Değişkenleri oku.
        include_vars: "{{ lookup('first_found', params) }}" # sana vereceğim yolda path içersinde bir liste var ve bunu kontrol et ve bana geri döndür anlamına geliyor.
        vars:
          params:
            files:
              - "vars/apache_{{ ansible_os_family }}.yml"
              - "vars/apache_default.yml"

      - name: this task targets apt package index update "Ubuntu Update index'ini günceller apache & Php yüklemesini yapar"
        ansible.builtin.package :
              name: 
                - "{{ apache_server }}"
                - "{{ php_libary }}"
              state: latest #Versiyon bilgisi
