---
  - hosts: all 
    become: true
    tasks:

    - name: this task targets apt package index update "Ubuntu Update index'ini günceller apache & Php yüklemesini yapar"
      ansible.builtin.package :
        name: 
          - "{{ apache_server }}"
          - "{{ php_libary }}"
        state: latest #Versiyon bilgisi
        update_cache: yes


